// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageFilter int32

const (
	// DEFAULT represents the default filter.
	ImageFilter_DEFAULT ImageFilter = 0
	// NEAREST represents nearest (crisp-edged) filter
	ImageFilter_NEAREST ImageFilter = 1
	// LINEAR represents linear filter
	ImageFilter_LINEAR ImageFilter = 2
)

var ImageFilter_name = map[int32]string{
	0: "DEFAULT",
	1: "NEAREST",
	2: "LINEAR",
}

var ImageFilter_value = map[string]int32{
	"DEFAULT": 0,
	"NEAREST": 1,
	"LINEAR":  2,
}

func (x ImageFilter) String() string {
	return proto.EnumName(ImageFilter_name, int32(x))
}

func (ImageFilter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type AtlasFile struct {
	Images               [][]byte          `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Filters              []ImageFilter     `protobuf:"varint,2,rep,packed,name=filters,proto3,enum=pb.ImageFilter" json:"filters,omitempty"`
	Frames               map[string]*Frame `protobuf:"bytes,3,rep,name=frames,proto3" json:"frames,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AtlasFile) Reset()         { *m = AtlasFile{} }
func (m *AtlasFile) String() string { return proto.CompactTextString(m) }
func (*AtlasFile) ProtoMessage()    {}
func (*AtlasFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *AtlasFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtlasFile.Unmarshal(m, b)
}
func (m *AtlasFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtlasFile.Marshal(b, m, deterministic)
}
func (m *AtlasFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtlasFile.Merge(m, src)
}
func (m *AtlasFile) XXX_Size() int {
	return xxx_messageInfo_AtlasFile.Size(m)
}
func (m *AtlasFile) XXX_DiscardUnknown() {
	xxx_messageInfo_AtlasFile.DiscardUnknown(m)
}

var xxx_messageInfo_AtlasFile proto.InternalMessageInfo

func (m *AtlasFile) GetImages() [][]byte {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *AtlasFile) GetFilters() []ImageFilter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *AtlasFile) GetFrames() map[string]*Frame {
	if m != nil {
		return m.Frames
	}
	return nil
}

type Frame struct {
	Image                uint32   `protobuf:"varint,1,opt,name=image,proto3" json:"image,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	W                    uint32   `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	H                    uint32   `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetImage() uint32 {
	if m != nil {
		return m.Image
	}
	return 0
}

func (m *Frame) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Frame) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Frame) GetW() uint32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Frame) GetH() uint32 {
	if m != nil {
		return m.H
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.ImageFilter", ImageFilter_name, ImageFilter_value)
	proto.RegisterType((*AtlasFile)(nil), "pb.AtlasFile")
	proto.RegisterMapType((map[string]*Frame)(nil), "pb.AtlasFile.FramesEntry")
	proto.RegisterType((*Frame)(nil), "pb.Frame")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0x07, 0xf0, 0x5f, 0x9a, 0x5f, 0x3b, 0xfa, 0x64, 0xd3, 0xf2, 0x20, 0x12, 0xbd, 0x58, 0x76,
	0xaa, 0x1e, 0x0a, 0x76, 0x17, 0xf1, 0x56, 0x58, 0x0b, 0x83, 0xe1, 0x21, 0x6e, 0x2f, 0xa0, 0x85,
	0xcc, 0x15, 0x3b, 0x57, 0xda, 0xe8, 0x96, 0x57, 0xe8, 0xdb, 0x92, 0x24, 0x53, 0x76, 0xeb, 0xe7,
	0xfb, 0xfc, 0x69, 0x12, 0x60, 0x4a, 0x77, 0x72, 0x48, 0xbb, 0x7e, 0xaf, 0xf6, 0xe8, 0x75, 0xf5,
	0xf4, 0x9b, 0x40, 0x98, 0xab, 0xb6, 0x1a, 0xca, 0xa6, 0x95, 0x78, 0x0d, 0x41, 0xb3, 0xab, 0xde,
	0xe4, 0xc0, 0x49, 0x4c, 0x93, 0xb1, 0x38, 0x09, 0xef, 0x61, 0xb4, 0x69, 0x5a, 0x25, 0xfb, 0x81,
	0x7b, 0x31, 0x4d, 0x2e, 0xb2, 0xcb, 0xb4, 0xab, 0xd3, 0x85, 0x29, 0x96, 0x36, 0x17, 0xbf, 0x75,
	0x7c, 0x84, 0x60, 0xd3, 0x57, 0x3b, 0x39, 0x70, 0x1a, 0xd3, 0x84, 0x65, 0x37, 0xa6, 0xf3, 0xef,
	0x0f, 0x69, 0x69, 0x6b, 0xc5, 0x87, 0xea, 0xb5, 0x38, 0x35, 0xde, 0xce, 0x81, 0x9d, 0xc5, 0x18,
	0x01, 0x7d, 0x97, 0x9a, 0x93, 0x98, 0x24, 0xa1, 0x30, 0x9f, 0x78, 0x07, 0xfe, 0x57, 0xd5, 0x7e,
	0x4a, 0xee, 0xc5, 0x24, 0x61, 0x59, 0x68, 0x56, 0xda, 0x09, 0xe1, 0xf2, 0x67, 0xef, 0x89, 0x4c,
	0xd7, 0xe0, 0xdb, 0x0c, 0xaf, 0xc0, 0xb7, 0xc7, 0xb6, 0x1b, 0x26, 0xc2, 0x01, 0xc7, 0x40, 0x8e,
	0x76, 0x7e, 0x22, 0xc8, 0xd1, 0x48, 0x73, 0xea, 0xa4, 0x8d, 0x0e, 0xfc, 0xbf, 0xd3, 0xc1, 0x68,
	0xcb, 0x7d, 0xa7, 0xed, 0xc3, 0x0c, 0xd8, 0xd9, 0x3d, 0x91, 0xc1, 0x68, 0x5e, 0x94, 0xf9, 0x7a,
	0xb9, 0x8a, 0xfe, 0x19, 0xbc, 0x14, 0xb9, 0x28, 0x5e, 0x57, 0x11, 0x41, 0x80, 0x60, 0xb9, 0x30,
	0x8c, 0xbc, 0x3a, 0xb0, 0x0f, 0x3c, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x48, 0x84, 0xb1,
	0x6f, 0x01, 0x00, 0x00,
}
