// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageFilter int32

const (
	// DEFAULT represents the default filter.
	ImageFilter_DEFAULT ImageFilter = 0
	// NEAREST represents nearest (crisp-edged) filter
	ImageFilter_NEAREST ImageFilter = 1
	// LINEAR represents linear filter
	ImageFilter_LINEAR ImageFilter = 2
)

var ImageFilter_name = map[int32]string{
	0: "DEFAULT",
	1: "NEAREST",
	2: "LINEAR",
}

var ImageFilter_value = map[string]int32{
	"DEFAULT": 0,
	"NEAREST": 1,
	"LINEAR":  2,
}

func (x ImageFilter) String() string {
	return proto.EnumName(ImageFilter_name, int32(x))
}

func (ImageFilter) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type AnimationClipMode int32

const (
	AnimationClipMode_ONCE          AnimationClipMode = 0
	AnimationClipMode_LOOP          AnimationClipMode = 1
	AnimationClipMode_PING_PONG     AnimationClipMode = 2
	AnimationClipMode_CLAMP_FOREVER AnimationClipMode = 4
)

var AnimationClipMode_name = map[int32]string{
	0: "ONCE",
	1: "LOOP",
	2: "PING_PONG",
	4: "CLAMP_FOREVER",
}

var AnimationClipMode_value = map[string]int32{
	"ONCE":          0,
	"LOOP":          1,
	"PING_PONG":     2,
	"CLAMP_FOREVER": 4,
}

func (x AnimationClipMode) String() string {
	return proto.EnumName(AnimationClipMode_name, int32(x))
}

func (AnimationClipMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

type AtlasFile struct {
	Images               [][]byte                  `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	Filters              []ImageFilter             `protobuf:"varint,2,rep,packed,name=filters,proto3,enum=pb.ImageFilter" json:"filters,omitempty"`
	Frames               map[string]*Frame         `protobuf:"bytes,3,rep,name=frames,proto3" json:"frames,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	AnimClips            map[string]*AnimationClip `protobuf:"bytes,4,rep,name=anim_clips,json=animClips,proto3" json:"anim_clips,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AtlasFile) Reset()         { *m = AtlasFile{} }
func (m *AtlasFile) String() string { return proto.CompactTextString(m) }
func (*AtlasFile) ProtoMessage()    {}
func (*AtlasFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *AtlasFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtlasFile.Unmarshal(m, b)
}
func (m *AtlasFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtlasFile.Marshal(b, m, deterministic)
}
func (m *AtlasFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtlasFile.Merge(m, src)
}
func (m *AtlasFile) XXX_Size() int {
	return xxx_messageInfo_AtlasFile.Size(m)
}
func (m *AtlasFile) XXX_DiscardUnknown() {
	xxx_messageInfo_AtlasFile.DiscardUnknown(m)
}

var xxx_messageInfo_AtlasFile proto.InternalMessageInfo

func (m *AtlasFile) GetImages() [][]byte {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *AtlasFile) GetFilters() []ImageFilter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *AtlasFile) GetFrames() map[string]*Frame {
	if m != nil {
		return m.Frames
	}
	return nil
}

func (m *AtlasFile) GetAnimClips() map[string]*AnimationClip {
	if m != nil {
		return m.AnimClips
	}
	return nil
}

type Frame struct {
	Image                uint32   `protobuf:"varint,1,opt,name=image,proto3" json:"image,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	W                    uint32   `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	H                    uint32   `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"`
	Ox                   int32    `protobuf:"varint,6,opt,name=ox,proto3" json:"ox,omitempty"`
	Oy                   int32    `protobuf:"varint,7,opt,name=oy,proto3" json:"oy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetImage() uint32 {
	if m != nil {
		return m.Image
	}
	return 0
}

func (m *Frame) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Frame) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Frame) GetW() uint32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Frame) GetH() uint32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *Frame) GetOx() int32 {
	if m != nil {
		return m.Ox
	}
	return 0
}

func (m *Frame) GetOy() int32 {
	if m != nil {
		return m.Oy
	}
	return 0
}

type AnimationClip struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fps                  float32           `protobuf:"fixed32,2,opt,name=fps,proto3" json:"fps,omitempty"`
	ClipMode             AnimationClipMode `protobuf:"varint,3,opt,name=clip_mode,json=clipMode,proto3,enum=pb.AnimationClipMode" json:"clip_mode,omitempty"`
	Frames               []*AnimFrame      `protobuf:"bytes,4,rep,name=frames,proto3" json:"frames,omitempty"`
	EndedEvent           *AnimationEvent   `protobuf:"bytes,5,opt,name=ended_event,json=endedEvent,proto3" json:"ended_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AnimationClip) Reset()         { *m = AnimationClip{} }
func (m *AnimationClip) String() string { return proto.CompactTextString(m) }
func (*AnimationClip) ProtoMessage()    {}
func (*AnimationClip) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *AnimationClip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimationClip.Unmarshal(m, b)
}
func (m *AnimationClip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimationClip.Marshal(b, m, deterministic)
}
func (m *AnimationClip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimationClip.Merge(m, src)
}
func (m *AnimationClip) XXX_Size() int {
	return xxx_messageInfo_AnimationClip.Size(m)
}
func (m *AnimationClip) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimationClip.DiscardUnknown(m)
}

var xxx_messageInfo_AnimationClip proto.InternalMessageInfo

func (m *AnimationClip) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnimationClip) GetFps() float32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *AnimationClip) GetClipMode() AnimationClipMode {
	if m != nil {
		return m.ClipMode
	}
	return AnimationClipMode_ONCE
}

func (m *AnimationClip) GetFrames() []*AnimFrame {
	if m != nil {
		return m.Frames
	}
	return nil
}

func (m *AnimationClip) GetEndedEvent() *AnimationEvent {
	if m != nil {
		return m.EndedEvent
	}
	return nil
}

type AnimFrame struct {
	X                    uint32          `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32          `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W                    uint32          `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H                    uint32          `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	Ox                   int32           `protobuf:"varint,5,opt,name=ox,proto3" json:"ox,omitempty"`
	Oy                   int32           `protobuf:"varint,6,opt,name=oy,proto3" json:"oy,omitempty"`
	Event                *AnimationEvent `protobuf:"bytes,7,opt,name=event,proto3" json:"event,omitempty"`
	Image                uint32          `protobuf:"varint,8,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AnimFrame) Reset()         { *m = AnimFrame{} }
func (m *AnimFrame) String() string { return proto.CompactTextString(m) }
func (*AnimFrame) ProtoMessage()    {}
func (*AnimFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *AnimFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimFrame.Unmarshal(m, b)
}
func (m *AnimFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimFrame.Marshal(b, m, deterministic)
}
func (m *AnimFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimFrame.Merge(m, src)
}
func (m *AnimFrame) XXX_Size() int {
	return xxx_messageInfo_AnimFrame.Size(m)
}
func (m *AnimFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimFrame.DiscardUnknown(m)
}

var xxx_messageInfo_AnimFrame proto.InternalMessageInfo

func (m *AnimFrame) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AnimFrame) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *AnimFrame) GetW() uint32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *AnimFrame) GetH() uint32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *AnimFrame) GetOx() int32 {
	if m != nil {
		return m.Ox
	}
	return 0
}

func (m *AnimFrame) GetOy() int32 {
	if m != nil {
		return m.Oy
	}
	return 0
}

func (m *AnimFrame) GetEvent() *AnimationEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *AnimFrame) GetImage() uint32 {
	if m != nil {
		return m.Image
	}
	return 0
}

type AnimationEvent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimationEvent) Reset()         { *m = AnimationEvent{} }
func (m *AnimationEvent) String() string { return proto.CompactTextString(m) }
func (*AnimationEvent) ProtoMessage()    {}
func (*AnimationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *AnimationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimationEvent.Unmarshal(m, b)
}
func (m *AnimationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimationEvent.Marshal(b, m, deterministic)
}
func (m *AnimationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimationEvent.Merge(m, src)
}
func (m *AnimationEvent) XXX_Size() int {
	return xxx_messageInfo_AnimationEvent.Size(m)
}
func (m *AnimationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AnimationEvent proto.InternalMessageInfo

func (m *AnimationEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnimationEvent) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.ImageFilter", ImageFilter_name, ImageFilter_value)
	proto.RegisterEnum("pb.AnimationClipMode", AnimationClipMode_name, AnimationClipMode_value)
	proto.RegisterType((*AtlasFile)(nil), "pb.AtlasFile")
	proto.RegisterMapType((map[string]*AnimationClip)(nil), "pb.AtlasFile.AnimClipsEntry")
	proto.RegisterMapType((map[string]*Frame)(nil), "pb.AtlasFile.FramesEntry")
	proto.RegisterType((*Frame)(nil), "pb.Frame")
	proto.RegisterType((*AnimationClip)(nil), "pb.AnimationClip")
	proto.RegisterType((*AnimFrame)(nil), "pb.AnimFrame")
	proto.RegisterType((*AnimationEvent)(nil), "pb.AnimationEvent")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0xce, 0xfa, 0x07, 0xf0, 0x38, 0xa6, 0x66, 0x95, 0x56, 0xdb, 0xa8, 0x52, 0x2d, 0xa4, 0xaa,
	0x6e, 0x0e, 0x48, 0x35, 0x97, 0x2a, 0x3d, 0x21, 0x62, 0x22, 0x24, 0x82, 0xd1, 0x36, 0xed, 0x15,
	0x99, 0xb0, 0x34, 0x56, 0xf1, 0x8f, 0xb0, 0x93, 0xe0, 0xe7, 0xe9, 0xb3, 0xf4, 0x11, 0xfa, 0x3e,
	0xd5, 0xee, 0x1a, 0x82, 0x9b, 0xe4, 0x36, 0xdf, 0xce, 0xcc, 0x37, 0x33, 0xdf, 0x8c, 0x0d, 0x66,
	0x51, 0x66, 0x2c, 0xef, 0x65, 0x9b, 0xb4, 0x48, 0xb1, 0x92, 0x2d, 0xba, 0x7f, 0x15, 0x30, 0x06,
	0xc5, 0x3a, 0xcc, 0x47, 0xd1, 0x9a, 0xe1, 0x37, 0xd0, 0x88, 0xe2, 0xf0, 0x27, 0xcb, 0x09, 0x72,
	0x54, 0xf7, 0x98, 0x56, 0x08, 0x7f, 0x82, 0xe6, 0x2a, 0x5a, 0x17, 0x6c, 0x93, 0x13, 0xc5, 0x51,
	0xdd, 0xb6, 0xf7, 0xaa, 0x97, 0x2d, 0x7a, 0x63, 0xee, 0x1c, 0x89, 0x77, 0xba, 0xf3, 0xe3, 0xcf,
	0xd0, 0x58, 0x6d, 0xc2, 0x98, 0xe5, 0x44, 0x75, 0x54, 0xd7, 0xf4, 0xde, 0xf2, 0xc8, 0x7d, 0x85,
	0xde, 0x48, 0xf8, 0xfc, 0xa4, 0xd8, 0x94, 0xb4, 0x0a, 0xc4, 0x5f, 0x01, 0xc2, 0x24, 0x8a, 0xe7,
	0x37, 0xeb, 0x28, 0xcb, 0x89, 0x26, 0xd2, 0xde, 0xd5, 0xd3, 0x06, 0x49, 0x14, 0x0f, 0xb9, 0x5b,
	0x66, 0x1a, 0xe1, 0x0e, 0x9f, 0x5e, 0x80, 0x79, 0xc0, 0x89, 0x6d, 0x50, 0x7f, 0xb1, 0x92, 0x20,
	0x07, 0xb9, 0x06, 0xe5, 0x26, 0x7e, 0x0f, 0xfa, 0x7d, 0xb8, 0xbe, 0x63, 0x44, 0x71, 0x90, 0x6b,
	0x7a, 0x06, 0x27, 0x16, 0x19, 0x54, 0xbe, 0x9f, 0x2b, 0x5f, 0xd0, 0x69, 0x00, 0xed, 0x7a, 0x89,
	0x67, 0x88, 0x3e, 0xd6, 0x89, 0x3a, 0xa2, 0xc3, 0x24, 0x8a, 0xc3, 0x22, 0x4a, 0x13, 0x9e, 0x79,
	0x40, 0xd8, 0xbd, 0x03, 0x5d, 0x14, 0xc1, 0x27, 0xa0, 0x0b, 0x11, 0x05, 0x93, 0x45, 0x25, 0xc0,
	0xc7, 0x80, 0xb6, 0x82, 0xc7, 0xa2, 0x68, 0xcb, 0x51, 0x49, 0x54, 0x89, 0x4a, 0x8e, 0x1e, 0x88,
	0x26, 0xd1, 0x03, 0x47, 0xb7, 0x44, 0x97, 0xe8, 0x16, 0xb7, 0x41, 0x49, 0xb7, 0xa4, 0xe1, 0x20,
	0x57, 0xa7, 0x4a, 0xba, 0x15, 0xb8, 0x24, 0xcd, 0x0a, 0x97, 0xdd, 0x3f, 0x08, 0xac, 0x5a, 0x4f,
	0x18, 0x83, 0x96, 0x84, 0x31, 0xab, 0x06, 0x11, 0x36, 0x9f, 0x6d, 0x95, 0xe5, 0xa2, 0xbe, 0x42,
	0xb9, 0x89, 0x3d, 0x30, 0xb8, 0xfa, 0xf3, 0x38, 0x5d, 0x32, 0xd1, 0x49, 0xdb, 0x7b, 0xfd, 0x64,
	0xbe, 0xab, 0x74, 0xc9, 0x68, 0xeb, 0xa6, 0xb2, 0xf0, 0x87, 0xfd, 0xa6, 0xe5, 0xca, 0xac, 0x5d,
	0x82, 0x54, 0x77, 0xb7, 0xdd, 0x3e, 0x98, 0x2c, 0x59, 0xb2, 0xe5, 0x9c, 0xdd, 0xb3, 0xa4, 0x10,
	0xa3, 0x98, 0x1e, 0xae, 0x91, 0xfb, 0xdc, 0x43, 0x41, 0x84, 0x09, 0xbb, 0xfb, 0x1b, 0x81, 0xb1,
	0xa7, 0x92, 0x6a, 0xa1, 0x9a, 0x5a, 0x4a, 0x4d, 0x2d, 0xb5, 0xa6, 0x96, 0x56, 0x57, 0x4b, 0xff,
	0x4f, 0xad, 0x9d, 0x7a, 0x25, 0x76, 0x41, 0x97, 0x4d, 0x35, 0x5f, 0x6c, 0x4a, 0x06, 0x3c, 0x6e,
	0xb1, 0x75, 0xb0, 0xc5, 0xee, 0xb9, 0xbc, 0x9a, 0xc7, 0xf0, 0x67, 0xd5, 0x3e, 0x39, 0xbc, 0x1b,
	0xa3, 0x3a, 0x92, 0xb3, 0x3e, 0x98, 0x07, 0xdf, 0x0f, 0x36, 0xa1, 0x79, 0xe1, 0x8f, 0x06, 0xdf,
	0x27, 0xd7, 0xf6, 0x11, 0x07, 0x53, 0x7f, 0x40, 0xfd, 0x6f, 0xd7, 0x36, 0xc2, 0x00, 0x8d, 0xc9,
	0x98, 0x43, 0x5b, 0x39, 0x1b, 0x43, 0xe7, 0xc9, 0x46, 0x70, 0x0b, 0xb4, 0x60, 0x3a, 0xf4, 0xed,
	0x23, 0x6e, 0x4d, 0x82, 0x60, 0x66, 0x23, 0x6c, 0x81, 0x31, 0x1b, 0x4f, 0x2f, 0xe7, 0xb3, 0x60,
	0x7a, 0x69, 0x2b, 0xb8, 0x03, 0xd6, 0x70, 0x32, 0xb8, 0x9a, 0xcd, 0x47, 0x01, 0xf5, 0x7f, 0xf8,
	0xd4, 0xd6, 0x16, 0x0d, 0xf1, 0x0f, 0xe8, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x23, 0x86, 0xe6,
	0xe1, 0x12, 0x04, 0x00, 0x00,
}
