// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package hello

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)









const uuidHelloSystem = "C435CD6B-100E-4440-8224-72497D18C6D8"

type viewHelloSystem struct {
    entities []VIHelloSystem
    world ecs.BaseWorld
    
}

type VIHelloSystem struct {
    Entity ecs.Entity
    
    Hello *Hello 
    
}

type sortedVIHelloSystems []VIHelloSystem
func (a sortedVIHelloSystems) Len() int           { return len(a) }
func (a sortedVIHelloSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVIHelloSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewHelloSystem(w ecs.BaseWorld) *viewHelloSystem {
    return &viewHelloSystem{
        entities: make([]VIHelloSystem, 0),
        world: w,
    }
}

func (v *viewHelloSystem) Matches() []VIHelloSystem {
    
    return v.entities
    
}

func (v *viewHelloSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewHelloSystem) Fetch(e ecs.Entity) (data VIHelloSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VIHelloSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewHelloSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VIHelloSystem{
        Entity: e,
        Hello: GetHelloComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVIHelloSystems(v.entities))
        }
    }
    return true
}

func (v *viewHelloSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewHelloSystem) rescan() {
    
    
    for _, x := range v.entities {
        e := x.Entity
        
        x.Hello = GetHelloComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// HelloSystem implements ecs.BaseSystem
type HelloSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewHelloSystem
    enabled     bool
    
}

// GetHelloSystem returns the instance of the system in a World
func GetHelloSystem(w ecs.BaseWorld) *HelloSystem {
    return w.S(uuidHelloSystem).(*HelloSystem)
}

// Enable system
func (s *HelloSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *HelloSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *HelloSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (HelloSystem) UUID() string {
    return "C435CD6B-100E-4440-8224-72497D18C6D8"
}

func (HelloSystem) Name() string {
    return "HelloSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchHelloSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchHelloSystem

func (s *HelloSystem) match(eflag ecs.Flag) bool {
    return matchHelloSystem(eflag, s.world)
}

func (s *HelloSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchHelloSystem(eflag, s.world)
}

func (s *HelloSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *HelloSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *HelloSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
        
    }
}

func (s *HelloSystem) V() *viewHelloSystem {
    return s.view
}

func (*HelloSystem) Priority() int64 {
    return 0
}

func (s *HelloSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("HelloSystem called Setup() more than once")
    }
    s.view = newviewHelloSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &HelloSystem{}
    })
}
