// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package hello

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidHelloComponent = "3E674178-4393-423A-9C07-99AD18C0CDD0"
const capHelloComponent = 256

type drawerHelloComponent struct {
    Entity ecs.Entity
    Data   Hello
}

// WatchHello is a helper struct to access a valid pointer of Hello
type WatchHello interface {
    Entity() ecs.Entity
    Data() *Hello
}

type slcdrawerHelloComponent []drawerHelloComponent
func (a slcdrawerHelloComponent) Len() int           { return len(a) }
func (a slcdrawerHelloComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerHelloComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchHello struct {
    c *HelloComponent
    entity ecs.Entity
}

func (w *mWatchHello) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchHello) Data() *Hello {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// HelloComponent implements ecs.BaseComponent
type HelloComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerHelloComponent
    
}

// GetHelloComponent returns the instance of the component in a World
func GetHelloComponent(w ecs.BaseWorld) *HelloComponent {
    return w.C(uuidHelloComponent).(*HelloComponent)
}

// SetHelloComponentData updates/adds a Hello to Entity e
func SetHelloComponentData(w ecs.BaseWorld, e ecs.Entity, data Hello) {
    GetHelloComponent(w).Upsert(e, data)
}

// GetHelloComponentData gets the *Hello of Entity e
func GetHelloComponentData(w ecs.BaseWorld, e ecs.Entity) *Hello {
    return GetHelloComponent(w).Data(e)
}

// WatchHelloComponentData gets a pointer getter of an entity's Hello.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchHelloComponentData(w ecs.BaseWorld, e ecs.Entity) WatchHello {
    return &mWatchHello{
        c: GetHelloComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (HelloComponent) UUID() string {
    return "3E674178-4393-423A-9C07-99AD18C0CDD0"
}

// Name implements ecs.BaseComponent
func (HelloComponent) Name() string {
    return "HelloComponent"
}

func (c *HelloComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetHelloComponentData to change component
// data outside of a system loop.
func (c *HelloComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(Hello)
    if !ok {
        panic("data must be Hello")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerHelloComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            sort.Sort(slcdrawerHelloComponent(c.data))
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "HelloComponent",
            ComponentID: "3E674178-4393-423A-9C07-99AD18C0CDD0",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "HelloComponent",
        ComponentID: "3E674178-4393-423A-9C07-99AD18C0CDD0",
        Entity: e,
    })
}

// Remove a Hello data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *HelloComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "HelloComponent",
        ComponentID: "3E674178-4393-423A-9C07-99AD18C0CDD0",
        Entity: e,
    })
}

func (c *HelloComponent) Data(e ecs.Entity) *Hello {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *HelloComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *HelloComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("HelloComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerHelloComponent, 0, 256)
    c.initialized = true
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &HelloComponent{}
    })
}
