// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package hello

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
    
)









const uuidMoveHelloSystem = "2E58680B-E13E-4763-A997-C744E4107820"

type viewMoveHelloSystem struct {
    entities []VIMoveHelloSystem
    world ecs.BaseWorld
    
}

type VIMoveHelloSystem struct {
    Entity ecs.Entity
    
    Hello *Hello 
    
    Move *Move 
    
}

type sortedVIMoveHelloSystems []VIMoveHelloSystem
func (a sortedVIMoveHelloSystems) Len() int           { return len(a) }
func (a sortedVIMoveHelloSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVIMoveHelloSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewMoveHelloSystem(w ecs.BaseWorld) *viewMoveHelloSystem {
    return &viewMoveHelloSystem{
        entities: make([]VIMoveHelloSystem, 0),
        world: w,
    }
}

func (v *viewMoveHelloSystem) Matches() []VIMoveHelloSystem {
    
    return v.entities
    
}

func (v *viewMoveHelloSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewMoveHelloSystem) Fetch(e ecs.Entity) (data VIMoveHelloSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VIMoveHelloSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewMoveHelloSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VIMoveHelloSystem{
        Entity: e,
        Hello: GetHelloComponent(v.world).Data(e),
Move: GetMoveComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVIMoveHelloSystems(v.entities))
        }
    }
    return true
}

func (v *viewMoveHelloSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewMoveHelloSystem) clearpointers() {
    
    
    for _, x := range v.entities {
        e := x.Entity
        
        x.Hello = nil
        
        x.Move = nil
        
        _ = e
    }
}

func (v *viewMoveHelloSystem) rescan() {
    
    
    for _, x := range v.entities {
        e := x.Entity
        
        x.Hello = GetHelloComponent(v.world).Data(e)
        
        x.Move = GetMoveComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// MoveHelloSystem implements ecs.BaseSystem
type MoveHelloSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewMoveHelloSystem
    enabled     bool
    
}

// GetMoveHelloSystem returns the instance of the system in a World
func GetMoveHelloSystem(w ecs.BaseWorld) *MoveHelloSystem {
    return w.S(uuidMoveHelloSystem).(*MoveHelloSystem)
}

// Enable system
func (s *MoveHelloSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *MoveHelloSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *MoveHelloSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (MoveHelloSystem) UUID() string {
    return "2E58680B-E13E-4763-A997-C744E4107820"
}

func (MoveHelloSystem) Name() string {
    return "MoveHelloSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchMoveHelloSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchMoveHelloSystem

func (s *MoveHelloSystem) match(eflag ecs.Flag) bool {
    return matchMoveHelloSystem(eflag, s.world)
}

func (s *MoveHelloSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchMoveHelloSystem(eflag, s.world)
}

func (s *MoveHelloSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *MoveHelloSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *MoveHelloSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
        
    }
}

func (s *MoveHelloSystem) ComponentWillResize(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        
        s.view.clearpointers()
    }
}

func (s *MoveHelloSystem) V() *viewMoveHelloSystem {
    return s.view
}

func (*MoveHelloSystem) Priority() int64 {
    return 10
}

func (s *MoveHelloSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("MoveHelloSystem called Setup() more than once")
    }
    s.view = newviewMoveHelloSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &MoveHelloSystem{}
    })
}
