// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package graphics

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidParticleEmitterComponent = "19A70DF9-0B1A-4A85-B23E-7BCA8E0857D7"
const capParticleEmitterComponent = 256

type drawerParticleEmitterComponent struct {
    Entity ecs.Entity
    Data   ParticleEmitter
}

// WatchParticleEmitter is a helper struct to access a valid pointer of ParticleEmitter
type WatchParticleEmitter interface {
    Entity() ecs.Entity
    Data() *ParticleEmitter
}

type slcdrawerParticleEmitterComponent []drawerParticleEmitterComponent
func (a slcdrawerParticleEmitterComponent) Len() int           { return len(a) }
func (a slcdrawerParticleEmitterComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerParticleEmitterComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchParticleEmitter struct {
    c *ParticleEmitterComponent
    entity ecs.Entity
}

func (w *mWatchParticleEmitter) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchParticleEmitter) Data() *ParticleEmitter {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// ParticleEmitterComponent implements ecs.BaseComponent
type ParticleEmitterComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerParticleEmitterComponent
    
}

// GetParticleEmitterComponent returns the instance of the component in a World
func GetParticleEmitterComponent(w ecs.BaseWorld) *ParticleEmitterComponent {
    return w.C(uuidParticleEmitterComponent).(*ParticleEmitterComponent)
}

// SetParticleEmitterComponentData updates/adds a ParticleEmitter to Entity e
func SetParticleEmitterComponentData(w ecs.BaseWorld, e ecs.Entity, data ParticleEmitter) {
    GetParticleEmitterComponent(w).Upsert(e, data)
}

// GetParticleEmitterComponentData gets the *ParticleEmitter of Entity e
func GetParticleEmitterComponentData(w ecs.BaseWorld, e ecs.Entity) *ParticleEmitter {
    return GetParticleEmitterComponent(w).Data(e)
}

// WatchParticleEmitterComponentData gets a pointer getter of an entity's ParticleEmitter.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchParticleEmitterComponentData(w ecs.BaseWorld, e ecs.Entity) WatchParticleEmitter {
    return &mWatchParticleEmitter{
        c: GetParticleEmitterComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (ParticleEmitterComponent) UUID() string {
    return "19A70DF9-0B1A-4A85-B23E-7BCA8E0857D7"
}

// Name implements ecs.BaseComponent
func (ParticleEmitterComponent) Name() string {
    return "ParticleEmitterComponent"
}

func (c *ParticleEmitterComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetParticleEmitterComponentData to change component
// data outside of a system loop.
func (c *ParticleEmitterComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(ParticleEmitter)
    if !ok {
        panic("data must be ParticleEmitter")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerParticleEmitterComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerParticleEmitterComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "ParticleEmitterComponent",
            ComponentID: "19A70DF9-0B1A-4A85-B23E-7BCA8E0857D7",
        })
    }
    c.onAdd(e)
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "ParticleEmitterComponent",
        ComponentID: "19A70DF9-0B1A-4A85-B23E-7BCA8E0857D7",
        Entity: e,
    })
}

// Remove a ParticleEmitter data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *ParticleEmitterComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    c.beforeRemove(e)
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "ParticleEmitterComponent",
        ComponentID: "19A70DF9-0B1A-4A85-B23E-7BCA8E0857D7",
        Entity: e,
    })
}

func (c *ParticleEmitterComponent) Data(e ecs.Entity) *ParticleEmitter {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *ParticleEmitterComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *ParticleEmitterComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("ParticleEmitterComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerParticleEmitterComponent, 0, 256)
    c.initialized = true
    c.onCompSetup()
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &ParticleEmitterComponent{}
    })
}
