// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package graphics

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidTextLabelComponent = "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76"
const capTextLabelComponent = 256

type drawerTextLabelComponent struct {
    Entity ecs.Entity
    Data   TextLabel
}

// WatchTextLabel is a helper struct to access a valid pointer of TextLabel
type WatchTextLabel interface {
    Entity() ecs.Entity
    Data() *TextLabel
}

type slcdrawerTextLabelComponent []drawerTextLabelComponent
func (a slcdrawerTextLabelComponent) Len() int           { return len(a) }
func (a slcdrawerTextLabelComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerTextLabelComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchTextLabel struct {
    c *TextLabelComponent
    entity ecs.Entity
}

func (w *mWatchTextLabel) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchTextLabel) Data() *TextLabel {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// TextLabelComponent implements ecs.BaseComponent
type TextLabelComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerTextLabelComponent
    
}

// GetTextLabelComponent returns the instance of the component in a World
func GetTextLabelComponent(w ecs.BaseWorld) *TextLabelComponent {
    return w.C(uuidTextLabelComponent).(*TextLabelComponent)
}

// SetTextLabelComponentData updates/adds a TextLabel to Entity e
func SetTextLabelComponentData(w ecs.BaseWorld, e ecs.Entity, data TextLabel) {
    GetTextLabelComponent(w).Upsert(e, data)
}

// GetTextLabelComponentData gets the *TextLabel of Entity e
func GetTextLabelComponentData(w ecs.BaseWorld, e ecs.Entity) *TextLabel {
    return GetTextLabelComponent(w).Data(e)
}

// WatchTextLabelComponentData gets a pointer getter of an entity's TextLabel.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchTextLabelComponentData(w ecs.BaseWorld, e ecs.Entity) WatchTextLabel {
    return &mWatchTextLabel{
        c: GetTextLabelComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (TextLabelComponent) UUID() string {
    return "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76"
}

// Name implements ecs.BaseComponent
func (TextLabelComponent) Name() string {
    return "TextLabelComponent"
}

func (c *TextLabelComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetTextLabelComponentData to change component
// data outside of a system loop.
func (c *TextLabelComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(TextLabel)
    if !ok {
        panic("data must be TextLabel")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerTextLabelComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerTextLabelComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "TextLabelComponent",
            ComponentID: "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "TextLabelComponent",
        ComponentID: "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76",
        Entity: e,
    })
}

// Remove a TextLabel data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *TextLabelComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "TextLabelComponent",
        ComponentID: "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76",
        Entity: e,
    })
}

func (c *TextLabelComponent) Data(e ecs.Entity) *TextLabel {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *TextLabelComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *TextLabelComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("TextLabelComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerTextLabelComponent, 0, 256)
    c.initialized = true
    c.onCompSetup()
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &TextLabelComponent{}
    })
}
