// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)









const uuidSoloDrawableSystem = "6389F54D-76C9-49FC-B3E3-1C73B334EBB6"

type viewSoloDrawableSystem struct {
    entities []VISoloDrawableSystem
    world ecs.BaseWorld
    
}

type VISoloDrawableSystem struct {
    Entity ecs.Entity
    
    Drawable *Drawable 
    
}

type sortedVISoloDrawableSystems []VISoloDrawableSystem
func (a sortedVISoloDrawableSystems) Len() int           { return len(a) }
func (a sortedVISoloDrawableSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVISoloDrawableSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewSoloDrawableSystem(w ecs.BaseWorld) *viewSoloDrawableSystem {
    return &viewSoloDrawableSystem{
        entities: make([]VISoloDrawableSystem, 0),
        world: w,
    }
}

func (v *viewSoloDrawableSystem) Matches() []VISoloDrawableSystem {
    
    return v.entities
    
}

func (v *viewSoloDrawableSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewSoloDrawableSystem) Fetch(e ecs.Entity) (data VISoloDrawableSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VISoloDrawableSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewSoloDrawableSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VISoloDrawableSystem{
        Entity: e,
        Drawable: GetDrawableComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVISoloDrawableSystems(v.entities))
        }
    }
    return true
}

func (v *viewSoloDrawableSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewSoloDrawableSystem) rescan() {
    
    
    for _, x := range v.entities {
        e := x.Entity
        
        x.Drawable = GetDrawableComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// SoloDrawableSystem implements ecs.BaseSystem
type SoloDrawableSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewSoloDrawableSystem
    enabled     bool
    
}

// GetSoloDrawableSystem returns the instance of the system in a World
func GetSoloDrawableSystem(w ecs.BaseWorld) *SoloDrawableSystem {
    return w.S(uuidSoloDrawableSystem).(*SoloDrawableSystem)
}

// Enable system
func (s *SoloDrawableSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *SoloDrawableSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *SoloDrawableSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (SoloDrawableSystem) UUID() string {
    return "6389F54D-76C9-49FC-B3E3-1C73B334EBB6"
}

func (SoloDrawableSystem) Name() string {
    return "SoloDrawableSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchSoloDrawableSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchSoloDrawableSystem

func (s *SoloDrawableSystem) match(eflag ecs.Flag) bool {
    return matchSoloDrawableSystem(eflag, s.world)
}

func (s *SoloDrawableSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchSoloDrawableSystem(eflag, s.world)
}

func (s *SoloDrawableSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *SoloDrawableSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *SoloDrawableSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
        
    }
}

func (s *SoloDrawableSystem) V() *viewSoloDrawableSystem {
    return s.view
}

func (*SoloDrawableSystem) Priority() int64 {
    return 0
}

func (s *SoloDrawableSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("SoloDrawableSystem called Setup() more than once")
    }
    s.view = newviewSoloDrawableSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &SoloDrawableSystem{}
    })
}
