// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)







const uuidFunctionComponent = "C1A2F07B-6EB2-4F83-B20B-0138073786BA"
const capFunctionComponent = 256

type drawerFunctionComponent struct {
    Entity ecs.Entity
    Data   Function
}

type slcdrawerFunctionComponent []drawerFunctionComponent
func (a slcdrawerFunctionComponent) Len() int           { return len(a) }
func (a slcdrawerFunctionComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerFunctionComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

// FunctionComponent implements ecs.BaseComponent
type FunctionComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerFunctionComponent
    
}

// GetFunctionComponent returns the instance of the component in a World
func GetFunctionComponent(w ecs.BaseWorld) *FunctionComponent {
    return w.C(uuidFunctionComponent).(*FunctionComponent)
}

// SetFunctionComponentData updates/adds a Function to Entity e
func SetFunctionComponentData(w ecs.BaseWorld, e ecs.Entity, data Function) {
    GetFunctionComponent(w).Upsert(e, data)
}

// GetFunctionComponentData gets the *Function of Entity e
func GetFunctionComponentData(w ecs.BaseWorld, e ecs.Entity) *Function {
    return GetFunctionComponent(w).Data(e)
}

// UUID implements ecs.BaseComponent
func (FunctionComponent) UUID() string {
    return "C1A2F07B-6EB2-4F83-B20B-0138073786BA"
}

// Name implements ecs.BaseComponent
func (FunctionComponent) Name() string {
    return "FunctionComponent"
}

func (c *FunctionComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetFunctionComponentData to change component
// data outside of a system loop.
func (c *FunctionComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(Function)
    if !ok {
        panic("data must be Function")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerFunctionComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            sort.Sort(slcdrawerFunctionComponent(c.data))
        }
    }
    
    c.world.CAdded(e, c, c.wkey)
    if rsz {
        c.world.CResized(c, c.wkey)
    }
    
}

// Remove a Function data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *FunctionComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
}

func (c *FunctionComponent) Data(e ecs.Entity) *Function {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *FunctionComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *FunctionComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("FunctionComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerFunctionComponent, 0, 256)
    c.initialized = true
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &FunctionComponent{}
    })
}
