// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidLabelComponent = "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76"
const capLabelComponent = 256

type drawerLabelComponent struct {
    Entity ecs.Entity
    Data   Label
}

// WatchLabel is a helper struct to access a valid pointer of Label
type WatchLabel interface {
    Entity() ecs.Entity
    Data() *Label
}

type slcdrawerLabelComponent []drawerLabelComponent
func (a slcdrawerLabelComponent) Len() int           { return len(a) }
func (a slcdrawerLabelComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerLabelComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchLabel struct {
    c *LabelComponent
    entity ecs.Entity
}

func (w *mWatchLabel) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchLabel) Data() *Label {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// LabelComponent implements ecs.BaseComponent
type LabelComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerLabelComponent
    
}

// GetLabelComponent returns the instance of the component in a World
func GetLabelComponent(w ecs.BaseWorld) *LabelComponent {
    return w.C(uuidLabelComponent).(*LabelComponent)
}

// SetLabelComponentData updates/adds a Label to Entity e
func SetLabelComponentData(w ecs.BaseWorld, e ecs.Entity, data Label) {
    GetLabelComponent(w).Upsert(e, data)
}

// GetLabelComponentData gets the *Label of Entity e
func GetLabelComponentData(w ecs.BaseWorld, e ecs.Entity) *Label {
    return GetLabelComponent(w).Data(e)
}

// WatchLabelComponentData gets a pointer getter of an entity's Label.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchLabelComponentData(w ecs.BaseWorld, e ecs.Entity) WatchLabel {
    return &mWatchLabel{
        c: GetLabelComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (LabelComponent) UUID() string {
    return "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76"
}

// Name implements ecs.BaseComponent
func (LabelComponent) Name() string {
    return "LabelComponent"
}

func (c *LabelComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetLabelComponentData to change component
// data outside of a system loop.
func (c *LabelComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(Label)
    if !ok {
        panic("data must be Label")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerLabelComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerLabelComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "LabelComponent",
            ComponentID: "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76",
        })
    }
    c.onAdd(e)
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "LabelComponent",
        ComponentID: "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76",
        Entity: e,
    })
}

// Remove a Label data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *LabelComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    c.beforeRemove(e)
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "LabelComponent",
        ComponentID: "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76",
        Entity: e,
    })
}

func (c *LabelComponent) Data(e ecs.Entity) *Label {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *LabelComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *LabelComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("LabelComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerLabelComponent, 0, 256)
    c.initialized = true
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &LabelComponent{}
    })
}
