// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)







const uuidLabelComponent = "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76"
const capLabelComponent = 256

type drawerLabelComponent struct {
    Entity ecs.Entity
    Data   Label
}

type slcdrawerLabelComponent []drawerLabelComponent
func (a slcdrawerLabelComponent) Len() int           { return len(a) }
func (a slcdrawerLabelComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerLabelComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

// LabelComponent implements ecs.BaseComponent
type LabelComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerLabelComponent
    
}

// GetLabelComponent returns the instance of the component in a World
func GetLabelComponent(w ecs.BaseWorld) *LabelComponent {
    return w.C(uuidLabelComponent).(*LabelComponent)
}

// SetLabelComponentData updates/adds a Label to Entity e
func SetLabelComponentData(w ecs.BaseWorld, e ecs.Entity, data Label) {
    GetLabelComponent(w).Upsert(e, data)
}

// GetLabelComponentData gets the *Label of Entity e
func GetLabelComponentData(w ecs.BaseWorld, e ecs.Entity) *Label {
    return GetLabelComponent(w).Data(e)
}

// UUID implements ecs.BaseComponent
func (LabelComponent) UUID() string {
    return "1A74D1BE-BBF7-44F4-AC8B-18A00208EB76"
}

// Name implements ecs.BaseComponent
func (LabelComponent) Name() string {
    return "LabelComponent"
}

func (c *LabelComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetLabelComponentData to change component
// data outside of a system loop.
func (c *LabelComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(Label)
    if !ok {
        panic("data must be Label")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerLabelComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            sort.Sort(slcdrawerLabelComponent(c.data))
        }
    }
    
    c.world.CAdded(e, c, c.wkey)
    if rsz {
        c.world.CResized(c, c.wkey)
    }
    
}

// Remove a Label data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *LabelComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
}

func (c *LabelComponent) Data(e ecs.Entity) *Label {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *LabelComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *LabelComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("LabelComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerLabelComponent, 0, 256)
    c.initialized = true
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &LabelComponent{}
    })
}
