// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
    
)









const uuidDrawableSpriteSystem = "02F3E9BD-CED3-4160-8943-9A89C0A533FB"

type viewDrawableSpriteSystem struct {
    entities []VIDrawableSpriteSystem
    world ecs.BaseWorld
    
}

type VIDrawableSpriteSystem struct {
    Entity ecs.Entity
    
    Drawable *Drawable 
    
    Sprite *Sprite 
    
}

type sortedVIDrawableSpriteSystems []VIDrawableSpriteSystem
func (a sortedVIDrawableSpriteSystems) Len() int           { return len(a) }
func (a sortedVIDrawableSpriteSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVIDrawableSpriteSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewDrawableSpriteSystem(w ecs.BaseWorld) *viewDrawableSpriteSystem {
    return &viewDrawableSpriteSystem{
        entities: make([]VIDrawableSpriteSystem, 0),
        world: w,
    }
}

func (v *viewDrawableSpriteSystem) Matches() []VIDrawableSpriteSystem {
    
    return v.entities
    
}

func (v *viewDrawableSpriteSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewDrawableSpriteSystem) Fetch(e ecs.Entity) (data VIDrawableSpriteSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VIDrawableSpriteSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewDrawableSpriteSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VIDrawableSpriteSystem{
        Entity: e,
        Drawable: GetDrawableComponent(v.world).Data(e),
Sprite: GetSpriteComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVIDrawableSpriteSystems(v.entities))
        }
    }
    return true
}

func (v *viewDrawableSpriteSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewDrawableSpriteSystem) clearpointers() {
    
    
    for i := range v.entities {
        e := v.entities[i].Entity
        
        v.entities[i].Drawable = nil
        
        v.entities[i].Sprite = nil
        
        _ = e
    }
}

func (v *viewDrawableSpriteSystem) rescan() {
    
    
    for i := range v.entities {
        e := v.entities[i].Entity
        
        v.entities[i].Drawable = GetDrawableComponent(v.world).Data(e)
        
        v.entities[i].Sprite = GetSpriteComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// DrawableSpriteSystem implements ecs.BaseSystem
type DrawableSpriteSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewDrawableSpriteSystem
    enabled     bool
    
}

// GetDrawableSpriteSystem returns the instance of the system in a World
func GetDrawableSpriteSystem(w ecs.BaseWorld) *DrawableSpriteSystem {
    return w.S(uuidDrawableSpriteSystem).(*DrawableSpriteSystem)
}

// Enable system
func (s *DrawableSpriteSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *DrawableSpriteSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *DrawableSpriteSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (DrawableSpriteSystem) UUID() string {
    return "02F3E9BD-CED3-4160-8943-9A89C0A533FB"
}

func (DrawableSpriteSystem) Name() string {
    return "DrawableSpriteSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchDrawableSpriteSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchDrawableSpriteSystem

func (s *DrawableSpriteSystem) match(eflag ecs.Flag) bool {
    return matchDrawableSpriteSystem(eflag, s.world)
}

func (s *DrawableSpriteSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchDrawableSpriteSystem(eflag, s.world)
}

func (s *DrawableSpriteSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            s.onEntityAdded(e)
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            s.onEntityRemoved(e)
        }
    }
}

func (s *DrawableSpriteSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            s.onEntityAdded(e)
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            s.onEntityRemoved(e)
        }
    }
}

func (s *DrawableSpriteSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
        s.onResize()
    }
}

func (s *DrawableSpriteSystem) ComponentWillResize(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        
        s.view.clearpointers()
    }
}

func (s *DrawableSpriteSystem) V() *viewDrawableSpriteSystem {
    return s.view
}

func (*DrawableSpriteSystem) Priority() int64 {
    return 10
}

func (s *DrawableSpriteSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("DrawableSpriteSystem called Setup() more than once")
    }
    s.view = newviewDrawableSpriteSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &DrawableSpriteSystem{}
    })
}
