// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)









const uuidSpriteAnimationSystem = "FFD3127E-6066-4561-8B2A-E1B59EBE489C"

type viewSpriteAnimationSystem struct {
    entities []VISpriteAnimationSystem
    world ecs.BaseWorld
    
}

type VISpriteAnimationSystem struct {
    Entity ecs.Entity
    
    Sprite *Sprite 
    
    SpriteAnimation *SpriteAnimation 
    
}

type sortedVISpriteAnimationSystems []VISpriteAnimationSystem
func (a sortedVISpriteAnimationSystems) Len() int           { return len(a) }
func (a sortedVISpriteAnimationSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVISpriteAnimationSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewSpriteAnimationSystem(w ecs.BaseWorld) *viewSpriteAnimationSystem {
    return &viewSpriteAnimationSystem{
        entities: make([]VISpriteAnimationSystem, 0),
        world: w,
    }
}

func (v *viewSpriteAnimationSystem) Matches() []VISpriteAnimationSystem {
    
    return v.entities
    
}

func (v *viewSpriteAnimationSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewSpriteAnimationSystem) Fetch(e ecs.Entity) (data VISpriteAnimationSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VISpriteAnimationSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewSpriteAnimationSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VISpriteAnimationSystem{
        Entity: e,
        Sprite: GetSpriteComponent(v.world).Data(e),
SpriteAnimation: GetSpriteAnimationComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVISpriteAnimationSystems(v.entities))
        }
    }
    return true
}

func (v *viewSpriteAnimationSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewSpriteAnimationSystem) rescan() {
    
    
    for _, x := range v.entities {
        e := x.Entity
        
        x.Sprite = GetSpriteComponent(v.world).Data(e)
        
        x.SpriteAnimation = GetSpriteAnimationComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// SpriteAnimationSystem implements ecs.BaseSystem
type SpriteAnimationSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewSpriteAnimationSystem
    enabled     bool
    
}

// GetSpriteAnimationSystem returns the instance of the system in a World
func GetSpriteAnimationSystem(w ecs.BaseWorld) *SpriteAnimationSystem {
    return w.S(uuidSpriteAnimationSystem).(*SpriteAnimationSystem)
}

// Enable system
func (s *SpriteAnimationSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *SpriteAnimationSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *SpriteAnimationSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (SpriteAnimationSystem) UUID() string {
    return "FFD3127E-6066-4561-8B2A-E1B59EBE489C"
}

func (SpriteAnimationSystem) Name() string {
    return "SpriteAnimationSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchSpriteAnimationSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchSpriteAnimationSystem

func (s *SpriteAnimationSystem) match(eflag ecs.Flag) bool {
    return matchSpriteAnimationSystem(eflag, s.world)
}

func (s *SpriteAnimationSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchSpriteAnimationSystem(eflag, s.world)
}

func (s *SpriteAnimationSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            s.onEntityAdded(e)
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            s.onEntityRemoved(e)
        }
    }
}

func (s *SpriteAnimationSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            s.onEntityAdded(e)
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            s.onEntityRemoved(e)
        }
    }
}

func (s *SpriteAnimationSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
    }
}

func (s *SpriteAnimationSystem) V() *viewSpriteAnimationSystem {
    return s.view
}

func (*SpriteAnimationSystem) Priority() int64 {
    return 12
}

func (s *SpriteAnimationSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("SpriteAnimationSystem called Setup() more than once")
    }
    s.view = newviewSpriteAnimationSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &SpriteAnimationSystem{}
    })
}
