// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)







const uuidSpriteAnimationComponent = "5A056275-C47D-44D2-994C-BD0AF107870C"
const capSpriteAnimationComponent = 256

type drawerSpriteAnimationComponent struct {
    Entity ecs.Entity
    Data   SpriteAnimation
}

type slcdrawerSpriteAnimationComponent []drawerSpriteAnimationComponent
func (a slcdrawerSpriteAnimationComponent) Len() int           { return len(a) }
func (a slcdrawerSpriteAnimationComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerSpriteAnimationComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

// SpriteAnimationComponent implements ecs.BaseComponent
type SpriteAnimationComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerSpriteAnimationComponent
    
}

// GetSpriteAnimationComponent returns the instance of the component in a World
func GetSpriteAnimationComponent(w ecs.BaseWorld) *SpriteAnimationComponent {
    return w.C(uuidSpriteAnimationComponent).(*SpriteAnimationComponent)
}

// SetSpriteAnimationComponentData updates/adds a SpriteAnimation to Entity e
func SetSpriteAnimationComponentData(w ecs.BaseWorld, e ecs.Entity, data SpriteAnimation) {
    GetSpriteAnimationComponent(w).Upsert(e, data)
}

// GetSpriteAnimationComponentData gets the *SpriteAnimation of Entity e
func GetSpriteAnimationComponentData(w ecs.BaseWorld, e ecs.Entity) *SpriteAnimation {
    return GetSpriteAnimationComponent(w).Data(e)
}

// UUID implements ecs.BaseComponent
func (SpriteAnimationComponent) UUID() string {
    return "5A056275-C47D-44D2-994C-BD0AF107870C"
}

// Name implements ecs.BaseComponent
func (SpriteAnimationComponent) Name() string {
    return "SpriteAnimationComponent"
}

func (c *SpriteAnimationComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetSpriteAnimationComponentData to change component
// data outside of a system loop.
func (c *SpriteAnimationComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(SpriteAnimation)
    if !ok {
        panic("data must be SpriteAnimation")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerSpriteAnimationComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            sort.Sort(slcdrawerSpriteAnimationComponent(c.data))
        }
    }
    
    c.world.CAdded(e, c, c.wkey)
    if rsz {
        c.world.CResized(c, c.wkey)
    }
    
}

// Remove a SpriteAnimation data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *SpriteAnimationComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
}

func (c *SpriteAnimationComponent) Data(e ecs.Entity) *SpriteAnimation {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *SpriteAnimationComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *SpriteAnimationComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("SpriteAnimationComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerSpriteAnimationComponent, 0, 256)
    c.initialized = true
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &SpriteAnimationComponent{}
    })
}
