// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)









const uuidDrawableTileSetSystem = "D02C8E02-E7C0-497B-B332-91543DF4FFFD"

type viewDrawableTileSetSystem struct {
    entities []VIDrawableTileSetSystem
    world ecs.BaseWorld
    
}

type VIDrawableTileSetSystem struct {
    Entity ecs.Entity
    
    Drawable *Drawable 
    
    TileSet *TileSet 
    
}

type sortedVIDrawableTileSetSystems []VIDrawableTileSetSystem
func (a sortedVIDrawableTileSetSystems) Len() int           { return len(a) }
func (a sortedVIDrawableTileSetSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVIDrawableTileSetSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewDrawableTileSetSystem(w ecs.BaseWorld) *viewDrawableTileSetSystem {
    return &viewDrawableTileSetSystem{
        entities: make([]VIDrawableTileSetSystem, 0),
        world: w,
    }
}

func (v *viewDrawableTileSetSystem) Matches() []VIDrawableTileSetSystem {
    
    return v.entities
    
}

func (v *viewDrawableTileSetSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewDrawableTileSetSystem) Fetch(e ecs.Entity) (data VIDrawableTileSetSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VIDrawableTileSetSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewDrawableTileSetSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VIDrawableTileSetSystem{
        Entity: e,
        Drawable: GetDrawableComponent(v.world).Data(e),
TileSet: GetTileSetComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVIDrawableTileSetSystems(v.entities))
        }
    }
    return true
}

func (v *viewDrawableTileSetSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewDrawableTileSetSystem) rescan() {
    
    
    for _, x := range v.entities {
        e := x.Entity
        
        x.Drawable = GetDrawableComponent(v.world).Data(e)
        
        x.TileSet = GetTileSetComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// DrawableTileSetSystem implements ecs.BaseSystem
type DrawableTileSetSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewDrawableTileSetSystem
    enabled     bool
    
}

// GetDrawableTileSetSystem returns the instance of the system in a World
func GetDrawableTileSetSystem(w ecs.BaseWorld) *DrawableTileSetSystem {
    return w.S(uuidDrawableTileSetSystem).(*DrawableTileSetSystem)
}

// Enable system
func (s *DrawableTileSetSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *DrawableTileSetSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *DrawableTileSetSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (DrawableTileSetSystem) UUID() string {
    return "D02C8E02-E7C0-497B-B332-91543DF4FFFD"
}

func (DrawableTileSetSystem) Name() string {
    return "DrawableTileSetSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchDrawableTileSetSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchDrawableTileSetSystem

func (s *DrawableTileSetSystem) match(eflag ecs.Flag) bool {
    return matchDrawableTileSetSystem(eflag, s.world)
}

func (s *DrawableTileSetSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchDrawableTileSetSystem(eflag, s.world)
}

func (s *DrawableTileSetSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            s.onEntityAdded(e)
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            s.onEntityRemoved(e)
        }
    }
}

func (s *DrawableTileSetSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            s.onEntityAdded(e)
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            s.onEntityRemoved(e)
        }
    }
}

func (s *DrawableTileSetSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
        s.onResize()
    }
}

func (s *DrawableTileSetSystem) V() *viewDrawableTileSetSystem {
    return s.view
}

func (*DrawableTileSetSystem) Priority() int64 {
    return 10
}

func (s *DrawableTileSetSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("DrawableTileSetSystem called Setup() more than once")
    }
    s.view = newviewDrawableTileSetSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &DrawableTileSetSystem{}
    })
}
