// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
)









const uuidDrawableTransformSystem = "7E9DEBA9-DEF6-4174-8160-AA7B72E2A734"

type viewDrawableTransformSystem struct {
    entities []VIDrawableTransformSystem
    world ecs.BaseWorld
    
}

type VIDrawableTransformSystem struct {
    Entity ecs.Entity
    
    Transform *Transform 
    
    Drawable *Drawable 
    
}

type sortedVIDrawableTransformSystems []VIDrawableTransformSystem
func (a sortedVIDrawableTransformSystems) Len() int           { return len(a) }
func (a sortedVIDrawableTransformSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVIDrawableTransformSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewDrawableTransformSystem(w ecs.BaseWorld) *viewDrawableTransformSystem {
    return &viewDrawableTransformSystem{
        entities: make([]VIDrawableTransformSystem, 0),
        world: w,
    }
}

func (v *viewDrawableTransformSystem) Matches() []VIDrawableTransformSystem {
    
    return v.entities
    
}

func (v *viewDrawableTransformSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewDrawableTransformSystem) Fetch(e ecs.Entity) (data VIDrawableTransformSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VIDrawableTransformSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewDrawableTransformSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VIDrawableTransformSystem{
        Entity: e,
        Transform: GetTransformComponent(v.world).Data(e),
Drawable: GetDrawableComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVIDrawableTransformSystems(v.entities))
        }
    }
    return true
}

func (v *viewDrawableTransformSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewDrawableTransformSystem) rescan() {
    
    
    for _, x := range v.entities {
        e := x.Entity
        
        x.Transform = GetTransformComponent(v.world).Data(e)
        
        x.Drawable = GetDrawableComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// DrawableTransformSystem implements ecs.BaseSystem
type DrawableTransformSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewDrawableTransformSystem
    enabled     bool
    
}

// GetDrawableTransformSystem returns the instance of the system in a World
func GetDrawableTransformSystem(w ecs.BaseWorld) *DrawableTransformSystem {
    return w.S(uuidDrawableTransformSystem).(*DrawableTransformSystem)
}

// Enable system
func (s *DrawableTransformSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *DrawableTransformSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *DrawableTransformSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (DrawableTransformSystem) UUID() string {
    return "7E9DEBA9-DEF6-4174-8160-AA7B72E2A734"
}

func (DrawableTransformSystem) Name() string {
    return "DrawableTransformSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchDrawableTransformSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchDrawableTransformSystem

func (s *DrawableTransformSystem) match(eflag ecs.Flag) bool {
    return matchDrawableTransformSystem(eflag, s.world)
}

func (s *DrawableTransformSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchDrawableTransformSystem(eflag, s.world)
}

func (s *DrawableTransformSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *DrawableTransformSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *DrawableTransformSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
    }
}

func (s *DrawableTransformSystem) V() *viewDrawableTransformSystem {
    return s.view
}

func (*DrawableTransformSystem) Priority() int64 {
    return 90
}

func (s *DrawableTransformSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("DrawableTransformSystem called Setup() more than once")
    }
    s.view = newviewDrawableTransformSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &DrawableTransformSystem{}
    })
}
