// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidTrTweeningComponent = "7D0BCDA8-ABE8-41EB-BF23-7DDCB4152AFD"
const capTrTweeningComponent = 256

type drawerTrTweeningComponent struct {
    Entity ecs.Entity
    Data   TrTweening
}

// WatchTrTweening is a helper struct to access a valid pointer of TrTweening
type WatchTrTweening interface {
    Entity() ecs.Entity
    Data() *TrTweening
}

type slcdrawerTrTweeningComponent []drawerTrTweeningComponent
func (a slcdrawerTrTweeningComponent) Len() int           { return len(a) }
func (a slcdrawerTrTweeningComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerTrTweeningComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchTrTweening struct {
    c *TrTweeningComponent
    entity ecs.Entity
}

func (w *mWatchTrTweening) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchTrTweening) Data() *TrTweening {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// TrTweeningComponent implements ecs.BaseComponent
type TrTweeningComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerTrTweeningComponent
    
}

// GetTrTweeningComponent returns the instance of the component in a World
func GetTrTweeningComponent(w ecs.BaseWorld) *TrTweeningComponent {
    return w.C(uuidTrTweeningComponent).(*TrTweeningComponent)
}

// SetTrTweeningComponentData updates/adds a TrTweening to Entity e
func SetTrTweeningComponentData(w ecs.BaseWorld, e ecs.Entity, data TrTweening) {
    GetTrTweeningComponent(w).Upsert(e, data)
}

// GetTrTweeningComponentData gets the *TrTweening of Entity e
func GetTrTweeningComponentData(w ecs.BaseWorld, e ecs.Entity) *TrTweening {
    return GetTrTweeningComponent(w).Data(e)
}

// WatchTrTweeningComponentData gets a pointer getter of an entity's TrTweening.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchTrTweeningComponentData(w ecs.BaseWorld, e ecs.Entity) WatchTrTweening {
    return &mWatchTrTweening{
        c: GetTrTweeningComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (TrTweeningComponent) UUID() string {
    return "7D0BCDA8-ABE8-41EB-BF23-7DDCB4152AFD"
}

// Name implements ecs.BaseComponent
func (TrTweeningComponent) Name() string {
    return "TrTweeningComponent"
}

func (c *TrTweeningComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetTrTweeningComponentData to change component
// data outside of a system loop.
func (c *TrTweeningComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(TrTweening)
    if !ok {
        panic("data must be TrTweening")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerTrTweeningComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerTrTweeningComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "TrTweeningComponent",
            ComponentID: "7D0BCDA8-ABE8-41EB-BF23-7DDCB4152AFD",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "TrTweeningComponent",
        ComponentID: "7D0BCDA8-ABE8-41EB-BF23-7DDCB4152AFD",
        Entity: e,
    })
}

// Remove a TrTweening data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *TrTweeningComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "TrTweeningComponent",
        ComponentID: "7D0BCDA8-ABE8-41EB-BF23-7DDCB4152AFD",
        Entity: e,
    })
}

func (c *TrTweeningComponent) Data(e ecs.Entity) *TrTweening {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *TrTweeningComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *TrTweeningComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("TrTweeningComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerTrTweeningComponent, 0, 256)
    c.initialized = true
    
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &TrTweeningComponent{}
    })
}
