// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidUIManagerComponent = "D81D8469-5C53-4436-9323-74635C5BF624"
const capUIManagerComponent = 256

type drawerUIManagerComponent struct {
    Entity ecs.Entity
    Data   UIManager
}

// WatchUIManager is a helper struct to access a valid pointer of UIManager
type WatchUIManager interface {
    Entity() ecs.Entity
    Data() *UIManager
}

type slcdrawerUIManagerComponent []drawerUIManagerComponent
func (a slcdrawerUIManagerComponent) Len() int           { return len(a) }
func (a slcdrawerUIManagerComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerUIManagerComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchUIManager struct {
    c *UIManagerComponent
    entity ecs.Entity
}

func (w *mWatchUIManager) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchUIManager) Data() *UIManager {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// UIManagerComponent implements ecs.BaseComponent
type UIManagerComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerUIManagerComponent
    
}

// GetUIManagerComponent returns the instance of the component in a World
func GetUIManagerComponent(w ecs.BaseWorld) *UIManagerComponent {
    return w.C(uuidUIManagerComponent).(*UIManagerComponent)
}

// SetUIManagerComponentData updates/adds a UIManager to Entity e
func SetUIManagerComponentData(w ecs.BaseWorld, e ecs.Entity, data UIManager) {
    GetUIManagerComponent(w).Upsert(e, data)
}

// GetUIManagerComponentData gets the *UIManager of Entity e
func GetUIManagerComponentData(w ecs.BaseWorld, e ecs.Entity) *UIManager {
    return GetUIManagerComponent(w).Data(e)
}

// WatchUIManagerComponentData gets a pointer getter of an entity's UIManager.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchUIManagerComponentData(w ecs.BaseWorld, e ecs.Entity) WatchUIManager {
    return &mWatchUIManager{
        c: GetUIManagerComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (UIManagerComponent) UUID() string {
    return "D81D8469-5C53-4436-9323-74635C5BF624"
}

// Name implements ecs.BaseComponent
func (UIManagerComponent) Name() string {
    return "UIManagerComponent"
}

func (c *UIManagerComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetUIManagerComponentData to change component
// data outside of a system loop.
func (c *UIManagerComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(UIManager)
    if !ok {
        panic("data must be UIManager")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerUIManagerComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerUIManagerComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "UIManagerComponent",
            ComponentID: "D81D8469-5C53-4436-9323-74635C5BF624",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "UIManagerComponent",
        ComponentID: "D81D8469-5C53-4436-9323-74635C5BF624",
        Entity: e,
    })
}

// Remove a UIManager data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *UIManagerComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "UIManagerComponent",
        ComponentID: "D81D8469-5C53-4436-9323-74635C5BF624",
        Entity: e,
    })
}

func (c *UIManagerComponent) Data(e ecs.Entity) *UIManager {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *UIManagerComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *UIManagerComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("UIManagerComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerUIManagerComponent, 0, 256)
    c.initialized = true
    c.onCompSetup()
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &UIManagerComponent{}
    })
}
