// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidUINodeComponent = "5ACA09B9-C488-46D7-A62E-5061C3DF5E6E"
const capUINodeComponent = 256

type drawerUINodeComponent struct {
    Entity ecs.Entity
    Data   UINode
}

// WatchUINode is a helper struct to access a valid pointer of UINode
type WatchUINode interface {
    Entity() ecs.Entity
    Data() *UINode
}

type slcdrawerUINodeComponent []drawerUINodeComponent
func (a slcdrawerUINodeComponent) Len() int           { return len(a) }
func (a slcdrawerUINodeComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerUINodeComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchUINode struct {
    c *UINodeComponent
    entity ecs.Entity
}

func (w *mWatchUINode) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchUINode) Data() *UINode {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// UINodeComponent implements ecs.BaseComponent
type UINodeComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerUINodeComponent
    
}

// GetUINodeComponent returns the instance of the component in a World
func GetUINodeComponent(w ecs.BaseWorld) *UINodeComponent {
    return w.C(uuidUINodeComponent).(*UINodeComponent)
}

// SetUINodeComponentData updates/adds a UINode to Entity e
func SetUINodeComponentData(w ecs.BaseWorld, e ecs.Entity, data UINode) {
    GetUINodeComponent(w).Upsert(e, data)
}

// GetUINodeComponentData gets the *UINode of Entity e
func GetUINodeComponentData(w ecs.BaseWorld, e ecs.Entity) *UINode {
    return GetUINodeComponent(w).Data(e)
}

// WatchUINodeComponentData gets a pointer getter of an entity's UINode.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchUINodeComponentData(w ecs.BaseWorld, e ecs.Entity) WatchUINode {
    return &mWatchUINode{
        c: GetUINodeComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (UINodeComponent) UUID() string {
    return "5ACA09B9-C488-46D7-A62E-5061C3DF5E6E"
}

// Name implements ecs.BaseComponent
func (UINodeComponent) Name() string {
    return "UINodeComponent"
}

func (c *UINodeComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetUINodeComponentData to change component
// data outside of a system loop.
func (c *UINodeComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(UINode)
    if !ok {
        panic("data must be UINode")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerUINodeComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerUINodeComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "UINodeComponent",
            ComponentID: "5ACA09B9-C488-46D7-A62E-5061C3DF5E6E",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "UINodeComponent",
        ComponentID: "5ACA09B9-C488-46D7-A62E-5061C3DF5E6E",
        Entity: e,
    })
}

// Remove a UINode data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *UINodeComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "UINodeComponent",
        ComponentID: "5ACA09B9-C488-46D7-A62E-5061C3DF5E6E",
        Entity: e,
    })
}

func (c *UINodeComponent) Data(e ecs.Entity) *UINode {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *UINodeComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *UINodeComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("UINodeComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerUINodeComponent, 0, 256)
    c.initialized = true
    
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &UINodeComponent{}
    })
}
