// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package core

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidUIRectComponent = "5895E095-CECF-4AA0-A3A2-44460FDFC3FB"
const capUIRectComponent = 256

type drawerUIRectComponent struct {
    Entity ecs.Entity
    Data   UIRect
}

// WatchUIRect is a helper struct to access a valid pointer of UIRect
type WatchUIRect interface {
    Entity() ecs.Entity
    Data() *UIRect
}

type slcdrawerUIRectComponent []drawerUIRectComponent
func (a slcdrawerUIRectComponent) Len() int           { return len(a) }
func (a slcdrawerUIRectComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerUIRectComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchUIRect struct {
    c *UIRectComponent
    entity ecs.Entity
}

func (w *mWatchUIRect) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchUIRect) Data() *UIRect {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// UIRectComponent implements ecs.BaseComponent
type UIRectComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerUIRectComponent
    
}

// GetUIRectComponent returns the instance of the component in a World
func GetUIRectComponent(w ecs.BaseWorld) *UIRectComponent {
    return w.C(uuidUIRectComponent).(*UIRectComponent)
}

// SetUIRectComponentData updates/adds a UIRect to Entity e
func SetUIRectComponentData(w ecs.BaseWorld, e ecs.Entity, data UIRect) {
    GetUIRectComponent(w).Upsert(e, data)
}

// GetUIRectComponentData gets the *UIRect of Entity e
func GetUIRectComponentData(w ecs.BaseWorld, e ecs.Entity) *UIRect {
    return GetUIRectComponent(w).Data(e)
}

// WatchUIRectComponentData gets a pointer getter of an entity's UIRect.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchUIRectComponentData(w ecs.BaseWorld, e ecs.Entity) WatchUIRect {
    return &mWatchUIRect{
        c: GetUIRectComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (UIRectComponent) UUID() string {
    return "5895E095-CECF-4AA0-A3A2-44460FDFC3FB"
}

// Name implements ecs.BaseComponent
func (UIRectComponent) Name() string {
    return "UIRectComponent"
}

func (c *UIRectComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetUIRectComponentData to change component
// data outside of a system loop.
func (c *UIRectComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(UIRect)
    if !ok {
        panic("data must be UIRect")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerUIRectComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerUIRectComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "UIRectComponent",
            ComponentID: "5895E095-CECF-4AA0-A3A2-44460FDFC3FB",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "UIRectComponent",
        ComponentID: "5895E095-CECF-4AA0-A3A2-44460FDFC3FB",
        Entity: e,
    })
}

// Remove a UIRect data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *UIRectComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "UIRectComponent",
        ComponentID: "5895E095-CECF-4AA0-A3A2-44460FDFC3FB",
        Entity: e,
    })
}

func (c *UIRectComponent) Data(e ecs.Entity) *UIRect {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *UIRectComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *UIRectComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("UIRectComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerUIRectComponent, 0, 256)
    c.initialized = true
    c.onCompSetup()
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &UIRectComponent{}
    })
}
