// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package components

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidCameraComponent = "02167024-81F4-4FEB-AC18-36564FCAC20B"
const capCameraComponent = 256

type drawerCameraComponent struct {
    Entity ecs.Entity
    Data   Camera
}

// WatchCamera is a helper struct to access a valid pointer of Camera
type WatchCamera interface {
    Entity() ecs.Entity
    Data() *Camera
}

type slcdrawerCameraComponent []drawerCameraComponent
func (a slcdrawerCameraComponent) Len() int           { return len(a) }
func (a slcdrawerCameraComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerCameraComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchCamera struct {
    c *CameraComponent
    entity ecs.Entity
}

func (w *mWatchCamera) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchCamera) Data() *Camera {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// CameraComponent implements ecs.BaseComponent
type CameraComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerCameraComponent
    
}

// GetCameraComponent returns the instance of the component in a World
func GetCameraComponent(w ecs.BaseWorld) *CameraComponent {
    return w.C(uuidCameraComponent).(*CameraComponent)
}

// SetCameraComponentData updates/adds a Camera to Entity e
func SetCameraComponentData(w ecs.BaseWorld, e ecs.Entity, data Camera) {
    GetCameraComponent(w).Upsert(e, data)
}

// GetCameraComponentData gets the *Camera of Entity e
func GetCameraComponentData(w ecs.BaseWorld, e ecs.Entity) *Camera {
    return GetCameraComponent(w).Data(e)
}

// WatchCameraComponentData gets a pointer getter of an entity's Camera.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchCameraComponentData(w ecs.BaseWorld, e ecs.Entity) WatchCamera {
    return &mWatchCamera{
        c: GetCameraComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (CameraComponent) UUID() string {
    return "02167024-81F4-4FEB-AC18-36564FCAC20B"
}

// Name implements ecs.BaseComponent
func (CameraComponent) Name() string {
    return "CameraComponent"
}

func (c *CameraComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetCameraComponentData to change component
// data outside of a system loop.
func (c *CameraComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(Camera)
    if !ok {
        panic("data must be Camera")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerCameraComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerCameraComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "CameraComponent",
            ComponentID: "02167024-81F4-4FEB-AC18-36564FCAC20B",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "CameraComponent",
        ComponentID: "02167024-81F4-4FEB-AC18-36564FCAC20B",
        Entity: e,
    })
}

// Remove a Camera data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *CameraComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "CameraComponent",
        ComponentID: "02167024-81F4-4FEB-AC18-36564FCAC20B",
        Entity: e,
    })
}

func (c *CameraComponent) Data(e ecs.Entity) *Camera {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *CameraComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *CameraComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("CameraComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerCameraComponent, 0, 256)
    c.initialized = true
    
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &CameraComponent{}
    })
}
