// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package components

import (
    
    "sort"

    "github.com/gabstv/ecs/v2"
    
)









const uuidFollowTransformSystem = "F06A8AE9-8615-4526-A266-E726F4BE0D8A"

type viewFollowTransformSystem struct {
    entities []VIFollowTransformSystem
    world ecs.BaseWorld
    
}

type VIFollowTransformSystem struct {
    Entity ecs.Entity
    
    Transform *Transform 
    
    FollowTransform *FollowTransform 
    
}

type sortedVIFollowTransformSystems []VIFollowTransformSystem
func (a sortedVIFollowTransformSystems) Len() int           { return len(a) }
func (a sortedVIFollowTransformSystems) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a sortedVIFollowTransformSystems) Less(i, j int) bool { return a[i].Entity < a[j].Entity }

func newviewFollowTransformSystem(w ecs.BaseWorld) *viewFollowTransformSystem {
    return &viewFollowTransformSystem{
        entities: make([]VIFollowTransformSystem, 0),
        world: w,
    }
}

func (v *viewFollowTransformSystem) Matches() []VIFollowTransformSystem {
    
    return v.entities
    
}

func (v *viewFollowTransformSystem) indexof(e ecs.Entity) int {
    i := sort.Search(len(v.entities), func(i int) bool { return v.entities[i].Entity >= e })
    if i < len(v.entities) && v.entities[i].Entity == e {
        return i
    }
    return -1
}

// Fetch a specific entity
func (v *viewFollowTransformSystem) Fetch(e ecs.Entity) (data VIFollowTransformSystem, ok bool) {
    
    i := v.indexof(e)
    if i == -1 {
        return VIFollowTransformSystem{}, false
    }
    return v.entities[i], true
}

func (v *viewFollowTransformSystem) Add(e ecs.Entity) bool {
    
    
    // MUST NOT add an Entity twice:
    if i := v.indexof(e); i > -1 {
        return false
    }
    v.entities = append(v.entities, VIFollowTransformSystem{
        Entity: e,
        Transform: GetTransformComponent(v.world).Data(e),
FollowTransform: GetFollowTransformComponent(v.world).Data(e),

    })
    if len(v.entities) > 1 {
        if v.entities[len(v.entities)-1].Entity < v.entities[len(v.entities)-2].Entity {
            sort.Sort(sortedVIFollowTransformSystems(v.entities))
        }
    }
    return true
}

func (v *viewFollowTransformSystem) Remove(e ecs.Entity) bool {
    
    
    if i := v.indexof(e); i != -1 {

        v.entities = append(v.entities[:i], v.entities[i+1:]...)
        return true
    }
    return false
}

func (v *viewFollowTransformSystem) clearpointers() {
    
    
    for i := range v.entities {
        e := v.entities[i].Entity
        
        v.entities[i].Transform = nil
        
        v.entities[i].FollowTransform = nil
        
        _ = e
    }
}

func (v *viewFollowTransformSystem) rescan() {
    
    
    for i := range v.entities {
        e := v.entities[i].Entity
        
        v.entities[i].Transform = GetTransformComponent(v.world).Data(e)
        
        v.entities[i].FollowTransform = GetFollowTransformComponent(v.world).Data(e)
        
        _ = e
        
    }
}

// FollowTransformSystem implements ecs.BaseSystem
type FollowTransformSystem struct {
    initialized bool
    world       ecs.BaseWorld
    view        *viewFollowTransformSystem
    enabled     bool
    
}

// GetFollowTransformSystem returns the instance of the system in a World
func GetFollowTransformSystem(w ecs.BaseWorld) *FollowTransformSystem {
    return w.S(uuidFollowTransformSystem).(*FollowTransformSystem)
}

// Enable system
func (s *FollowTransformSystem) Enable() {
    s.enabled = true
}

// Disable system
func (s *FollowTransformSystem) Disable() {
    s.enabled = false
}

// Enabled checks if enabled
func (s *FollowTransformSystem) Enabled() bool {
    return s.enabled
}

// UUID implements ecs.BaseSystem
func (FollowTransformSystem) UUID() string {
    return "F06A8AE9-8615-4526-A266-E726F4BE0D8A"
}

func (FollowTransformSystem) Name() string {
    return "FollowTransformSystem"
}

// ensure matchfn
var _ ecs.MatchFn = matchFollowTransformSystem

// ensure resizematchfn
var _ ecs.MatchFn = resizematchFollowTransformSystem

func (s *FollowTransformSystem) match(eflag ecs.Flag) bool {
    return matchFollowTransformSystem(eflag, s.world)
}

func (s *FollowTransformSystem) resizematch(eflag ecs.Flag) bool {
    return resizematchFollowTransformSystem(eflag, s.world)
}

func (s *FollowTransformSystem) ComponentAdded(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *FollowTransformSystem) ComponentRemoved(e ecs.Entity, eflag ecs.Flag) {
    if s.match(eflag) {
        if s.view.Add(e) {
            // TODO: dispatch event that this entity was added to this system
            
        }
    } else {
        if s.view.Remove(e) {
            // TODO: dispatch event that this entity was removed from this system
            
        }
    }
}

func (s *FollowTransformSystem) ComponentResized(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        s.view.rescan()
        
    }
}

func (s *FollowTransformSystem) ComponentWillResize(cflag ecs.Flag) {
    if s.resizematch(cflag) {
        
        s.view.clearpointers()
    }
}

func (s *FollowTransformSystem) V() *viewFollowTransformSystem {
    return s.view
}

func (*FollowTransformSystem) Priority() int64 {
    return 60
}

func (s *FollowTransformSystem) Setup(w ecs.BaseWorld) {
    if s.initialized {
        panic("FollowTransformSystem called Setup() more than once")
    }
    s.view = newviewFollowTransformSystem(w)
    s.world = w
    s.enabled = true
    s.initialized = true
    
}


func init() {
    ecs.RegisterSystem(func() ecs.BaseSystem {
        return &FollowTransformSystem{}
    })
}
