// Code generated by ecs https://github.com/gabstv/ecs; DO NOT EDIT.

package ggui

import (
    "sort"
    

    "github.com/gabstv/ecs/v2"
)








const uuidUIAnchorComponent = "D7052642-7A15-44B0-81AA-4B84F49DA9E0"
const capUIAnchorComponent = 256

type drawerUIAnchorComponent struct {
    Entity ecs.Entity
    Data   UIAnchor
}

// WatchUIAnchor is a helper struct to access a valid pointer of UIAnchor
type WatchUIAnchor interface {
    Entity() ecs.Entity
    Data() *UIAnchor
}

type slcdrawerUIAnchorComponent []drawerUIAnchorComponent
func (a slcdrawerUIAnchorComponent) Len() int           { return len(a) }
func (a slcdrawerUIAnchorComponent) Swap(i, j int)      { a[i], a[j] = a[j], a[i] }
func (a slcdrawerUIAnchorComponent) Less(i, j int) bool { return a[i].Entity < a[j].Entity }


type mWatchUIAnchor struct {
    c *UIAnchorComponent
    entity ecs.Entity
}

func (w *mWatchUIAnchor) Entity() ecs.Entity {
    return w.entity
}

func (w *mWatchUIAnchor) Data() *UIAnchor {
    
    
    id := w.c.indexof(w.entity)
    if id == -1 {
        return nil
    }
    return &w.c.data[id].Data
}

// UIAnchorComponent implements ecs.BaseComponent
type UIAnchorComponent struct {
    initialized bool
    flag        ecs.Flag
    world       ecs.BaseWorld
    wkey        [4]byte
    data        []drawerUIAnchorComponent
    
}

// GetUIAnchorComponent returns the instance of the component in a World
func GetUIAnchorComponent(w ecs.BaseWorld) *UIAnchorComponent {
    return w.C(uuidUIAnchorComponent).(*UIAnchorComponent)
}

// SetUIAnchorComponentData updates/adds a UIAnchor to Entity e
func SetUIAnchorComponentData(w ecs.BaseWorld, e ecs.Entity, data UIAnchor) {
    GetUIAnchorComponent(w).Upsert(e, data)
}

// GetUIAnchorComponentData gets the *UIAnchor of Entity e
func GetUIAnchorComponentData(w ecs.BaseWorld, e ecs.Entity) *UIAnchor {
    return GetUIAnchorComponent(w).Data(e)
}

// WatchUIAnchorComponentData gets a pointer getter of an entity's UIAnchor.
//
// The pointer must not be stored because it may become invalid overtime.
func WatchUIAnchorComponentData(w ecs.BaseWorld, e ecs.Entity) WatchUIAnchor {
    return &mWatchUIAnchor{
        c: GetUIAnchorComponent(w),
        entity: e,
    }
}

// UUID implements ecs.BaseComponent
func (UIAnchorComponent) UUID() string {
    return "D7052642-7A15-44B0-81AA-4B84F49DA9E0"
}

// Name implements ecs.BaseComponent
func (UIAnchorComponent) Name() string {
    return "UIAnchorComponent"
}

func (c *UIAnchorComponent) indexof(e ecs.Entity) int {
    i := sort.Search(len(c.data), func(i int) bool { return c.data[i].Entity >= e })
    if i < len(c.data) && c.data[i].Entity == e {
        return i
    }
    return -1
}

// Upsert creates or updates a component data of an entity.
// Not recommended to be used directly. Use SetUIAnchorComponentData to change component
// data outside of a system loop.
func (c *UIAnchorComponent) Upsert(e ecs.Entity, data interface{}) {
    v, ok := data.(UIAnchor)
    if !ok {
        panic("data must be UIAnchor")
    }
    
    id := c.indexof(e)
    
    if id > -1 {
        
        dwr := &c.data[id]
        dwr.Data = v
        
        return
    }
    
    rsz := false
    if cap(c.data) == len(c.data) {
        rsz = true
        c.world.CWillResize(c, c.wkey)
        
    }
    newindex := len(c.data)
    c.data = append(c.data, drawerUIAnchorComponent{
        Entity: e,
        Data:   v,
    })
    if len(c.data) > 1 {
        if c.data[newindex].Entity < c.data[newindex-1].Entity {
            c.world.CWillResize(c, c.wkey)
            
            sort.Sort(slcdrawerUIAnchorComponent(c.data))
            rsz = true
        }
    }
    
    if rsz {
        
        c.world.CResized(c, c.wkey)
        c.world.Dispatch(ecs.Event{
            Type: ecs.EvtComponentsResized,
            ComponentName: "UIAnchorComponent",
            ComponentID: "D7052642-7A15-44B0-81AA-4B84F49DA9E0",
        })
    }
    
    c.world.CAdded(e, c, c.wkey)
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentAdded,
        ComponentName: "UIAnchorComponent",
        ComponentID: "D7052642-7A15-44B0-81AA-4B84F49DA9E0",
        Entity: e,
    })
}

// Remove a UIAnchor data from entity e
//
// Warning: DO NOT call remove inside the system entities loop
func (c *UIAnchorComponent) Remove(e ecs.Entity) {
    
    
    i := c.indexof(e)
    if i == -1 {
        return
    }
    
    //c.data = append(c.data[:i], c.data[i+1:]...)
    c.data = c.data[:i+copy(c.data[i:], c.data[i+1:])]
    c.world.CRemoved(e, c, c.wkey)
    
    c.world.Dispatch(ecs.Event{
        Type: ecs.EvtComponentRemoved,
        ComponentName: "UIAnchorComponent",
        ComponentID: "D7052642-7A15-44B0-81AA-4B84F49DA9E0",
        Entity: e,
    })
}

func (c *UIAnchorComponent) Data(e ecs.Entity) *UIAnchor {
    
    
    index := c.indexof(e)
    if index > -1 {
        return &c.data[index].Data
    }
    return nil
}

// Flag returns the 
func (c *UIAnchorComponent) Flag() ecs.Flag {
    return c.flag
}

// Setup is called by ecs.BaseWorld
//
// Do not call this directly
func (c *UIAnchorComponent) Setup(w ecs.BaseWorld, f ecs.Flag, key [4]byte) {
    if c.initialized {
        panic("UIAnchorComponent called Setup() more than once")
    }
    c.flag = f
    c.world = w
    c.wkey = key
    c.data = make([]drawerUIAnchorComponent, 0, 256)
    c.initialized = true
    
}


func init() {
    ecs.RegisterComponent(func() ecs.BaseComponent {
        return &UIAnchorComponent{}
    })
}
