name: UnitTests

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches:
      - master
      - develop
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up *nix dependencies
        run: |
          sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r"
          sudo apt-get install libasound2-dev libglew-dev libgles2-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        env:
          DISPLAY: ":99.0"
        run: xvfb-run --auto-servernum go test -race -v ./...